
import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "es";

type TranslationEntry = {
  en: string;
};

type TranslationDictionary = {
  [key: string]: TranslationEntry;
};

// A simplified translation dictionary that only contains English translations
const translations: TranslationDictionary = {
  // Navigation
  "Inicio": { en: "Home" },
  "Punto de Venta": { en: "Point of Sale" },
  "Empleados": { en: "Employees" },
  "Menú": { en: "Menu" },
  "Inventario": { en: "Inventory" },
  "Lista de Órdenes": { en: "Orders" },
  "Reportes": { en: "Reports" },
  "Personalizaciones": { en: "Customizations" },
  "Configuración": { en: "Settings" },
  
  // Common Words
  "Guardar": { en: "Save" },
  "Cancelar": { en: "Cancel" },
  "Eliminar": { en: "Delete" },
  "Editar": { en: "Edit" },
  "Nuevo": { en: "New" },
  "Buscar": { en: "Search" },
  "Filtrar": { en: "Filter" },
  "Detalles": { en: "Details" },
  "Cerrar": { en: "Close" },
  "Cerrar sesión": { en: "Log Out" },
  "Aceptar": { en: "Accept" },
  "Rechazar": { en: "Reject" },
  "Siguiente": { en: "Next" },
  "Anterior": { en: "Previous" },
  "Volver": { en: "Back" },
  "Ingresa el código": { en: "Enter code" },
  "Por favor ingresa un código de acceso.": { en: "Please enter an access code." },
  "Bienvenido": { en: "Welcome" },
  "Código inválido": { en: "Invalid Code" },
  "Código de acceso no reconocido.": { en: "Access code not recognized." },
  "Error al validar el código.": { en: "Failed to validate code." },
  "Introduce el código de acceso": { en: "Enter Access Code" },
  "Entrar": { en: "Enter" },
  "Mesas seleccionadas": { en: "Selected tables" },
  "Cancelar Fusión": { en: "Cancel Merge" },
  "Iniciar Orden Fusionada": { en: "Start Merged Order" },
  "Enlazando": { en: "Linking" },
  "Cancelar Enlace": { en: "Cancel Link" },
  "Confirmar Enlace": { en: "Confirm Link" },
  "Gestión de Órdenes": { en: "Order Management" },
  "Administra tus órdenes activas": { en: "Manage your active orders" },
  "Nueva Orden": { en: "New Order" },
  "Órdenes Pendientes": { en: "Pending Orders" },
  "En Cocina": { en: "In Kitchen" },
  "Por Pagar": { en: "To Pay" },
  "Ingresos Activos": { en: "Active Revenue" },
  "Todas las Órdenes": { en: "All Orders" },
  "Pendiente": { en: "Pending" },
  "En Espera": { en: "On Hold" },
  "Preparando": { en: "Preparing" },
  "Servidas": { en: "Served" },
  "Marcar como Servida": { en: "Mark as Served" },
  "Pagadas": { en: "Paid" },
  "Canceladas": { en: "Cancelled" },
  "Mis Órdenes Activas": { en: "My Active Orders" },
  "No se encontraron órdenes activas": { en: "No active orders found" },
  "Crear Nueva Orden": { en: "Create New Order" },
  "Para llevar": { en: "Takeout" },
  "cliente(s)": { en: "client(s)" },
  "Iniciada a las": { en: "Started at" },
  "Ver": { en: "View" },
  "Agregar Artículos": { en: "Add Items" },
  "Pagar": { en: "Pay" },
  "Detalles de Orden": { en: "Order Details" },
  "ID de Orden": { en: "Order ID" },
  "Creada": { en: "Created" },
  "Mesero": { en: "Server" },
  "Clientes": { en: "Clients" },
  "Artículos de la Orden": { en: "Order Items" },
  "Procesar Pago": { en: "Process Payment" },
  "Confirmar Fusión": { en: "Confirm Merge" },
  "¿Deseas fusionar la orden de la Mesa": { en: "Do you want to merge the order from Table" },
  "a la Mesa": { en: "to Table" },
  "Fusionando...": { en: "Merging..." },
  "Confirmar": { en: "Confirm" },
  "Confirmar Cambio de Mesa": { en: "Confirm Table Change" },
  "Mover orden de la Mesa": { en: "Move order from Table" },
  "Moviendo...": { en: "Moving..." },
  "Desvincular Mesa": { en: "Unlink Table" },
  "Elige cómo desvincular la mesa": { en: "Choose how to unlink table" },
  "Desvinculando...": { en: "Unlinking..." },
  "Desvincular Esta Mesa": { en: "Unlink This Table" },
  "Desvincular Todo el Grupo": { en: "Unlink Entire Group" },
  "Selecciona Número de Clientes": { en: "Select Number of Guests" },
  "Selecciona número de clientes (máx": { en: "Select number of guests (max" },

  "Subcategoría": { en: "Subcategory" },
  "Descripción": { en: "Description" },
  "Busca grupos de personalización para añadir a este producto": { en: "Search for customization groups to add to this product" },
  
  // POS
  "Categorías": { en: "Categories" },
  "Todas": { en: "All" },
  "Añadir a Orden": { en: "Add to Order" },
  "Mesa": { en: "Table" },
  "Cliente": { en: "Customer" },
  "Elementos": { en: "Items" },
  "Cantidad": { en: "Quantity" },
  "Precio": { en: "Price" },
  "Subtotal": { en: "Subtotal" },
  "Impuesto": { en: "Tax" },
  "Total": { en: "Total" },
  "Descuento": { en: "Discount" },
  "Propina": { en: "Tip" },
  "Pagar": { en: "Pay" },
  "Imprimir": { en: "Print" },
  "Cancelar Orden": { en: "Cancel Order" },
  "Modificar": { en: "Modify" },
  "Agregar Nota": { en: "Add Note" },
  "Sin elementos en la orden": { en: "No items in order" },
  "Agregar productos para continuar": { en: "Add products to continue" },
  "Resumen de Orden": { en: "Order Summary" },
  "Nueva Orden": { en: "New Order" },
  "Orden para": { en: "Order for" },
  "Para llevar": { en: "To Go" },
  "Para comer aquí": { en: "Dine In" },
  "Métodos de Pago": { en: "Payment Methods" },
  "Efectivo": { en: "Cash" },
  "Tarjeta": { en: "Card" },
  "Confirmar Pago": { en: "Confirm Payment" },
  "Orden Completada": { en: "Order Completed" },
  "Note": { en: "Note" },
  "Payment confirmed and order processed successfully.": { en: "Payment confirmed and order processed successfully." },
  
  // Menu Page
  "Gestión del Menú": { en: "Menu Management" },
  "Desayuno": { en: "Breakfast" },
  "Almuerzo": { en: "Lunch" },
  "Cena": { en: "Dinner" },
  "Menú de Desayuno": { en: "Breakfast Menu" },
  "Menú de Almuerzo": { en: "Lunch Menu" },
  "Menú de Cena": { en: "Dinner Menu" },
  "Edición de producto": { en: "Product Editing" },
  "Agregar Producto": { en: "Add Product" },
  "Agregar nuevo producto": { en: "Add New Product" },
  "Agregar Categoría": { en: "Add Category" },
  "Editar Categorías": { en: "Edit Categories" },
  "Agregar Subcategoría": { en: "Add Subcategory" },
  
  // Inventory Page
  "Dashboard de Inventario": { en: "Inventory Dashboard" },
  "Estado de Inventario": { en: "Inventory Status" },
  "Costeo de Recetas": { en: "Recipe Costing" },
  "Producto": { en: "Product" },
  "Categoría": { en: "Category" },
  "Estado": { en: "Status" },
  "Costo": { en: "Cost" },
  "Alto": { en: "High" },
  "Medio": { en: "Medium" },
  "Bajo": { en: "Low" },
  "Alerta de Inventario": { en: "Inventory Alert" },
  "productos están por debajo del nivel mínimo requerido": { en: "products are below the minimum required level" },
  "Carnes": { en: "Meats" },
  "Lácteos": { en: "Dairy" },
  "Panadería": { en: "Bakery" },
  "Vegetales": { en: "Vegetables" },
  "Congelados": { en: "Frozen" },
  "Bebidas": { en: "Beverages" },
  "Insumos": { en: "Supplies" },
  "Costo de Ingredientes": { en: "Ingredients Cost" },
  "Precio de Venta": { en: "Selling Price" },
  "Beneficio": { en: "Profit" },
  "Margen %": { en: "Margin %" },
  "Proveedor": { en: "Supplier" },
  "Unidad": { en: "Unit" },
  "Costo por Unidad": { en: "Cost per Unit" },
  "No especificado": { en: "Not specified" },
  "No hay productos en el inventario": { en: "No products in inventory" },
  "Introduce la información del producto para añadirlo al inventario.": { en: "Enter product information to add it to inventory." },
  "Vista previa de imagen": { en: "Image preview" },
  "Subir imagen": { en: "Upload image" },
  "Guardando...": { en: "Saving..." },
  "Cambiar imagen": { en: "Change image" },
  "Producto agregado": { en: "Product added" },
  "El producto ha sido agregado al inventario": { en: "The product has been added to the inventory" },
  "No se pudo agregar el producto": { en: "Could not add the product" },
  "Producto actualizado": { en: "Product updated" },
  "El producto ha sido actualizado correctamente": { en: "The product has been updated successfully" },
  "No se pudo actualizar el producto": { en: "Could not update the product" },
  "Producto eliminado": { en: "Product deleted" },
  "El producto ha sido eliminado del inventario": { en: "The product has been removed from inventory" },
  "No se pudo eliminar el producto": { en: "Could not delete the product" },
  "¿Estás seguro de que quieres eliminar este producto?": { en: "Are you sure you want to delete this product?" },
  "Editar Producto": { en: "Edit Product" },
  "Modifica la información del producto.": { en: "Modify the product information." },
  "Cargando inventario...": { en: "Loading inventory..." },
  "No se pudo cargar el inventario": { en: "Could not load inventory" },
  "Image": { en: "Image" },
  "Actions": { en: "Actions" },
  
  
  // Employees
  "Gestión de Empleados": { en: "Employee Management" },
  "Gestión de Personal": { en: "Staff Management" },
  "Administra a tus empleados y permisos": { en: "Manage your employees and permissions" },
  "Empleados Activos": { en: "Active Employees" },
  "Personal actualmente en turno": { en: "Staff currently on shift" },
  "Empleados Inactivos": { en: "Inactive Employees" },
  "Personal disponible para turno": { en: "Staff available for shift" },
  "Registro de Horas": { en: "Time Records" },
  "Resumen de horas y propinas": { en: "Summary of hours and tips" },
  "No hay empleados activos en este momento": { en: "No active employees at this time" },
  "No hay empleados inactivos en este momento": { en: "No inactive employees at this time" },
  "Nombre": { en: "Name" },
  "Cargo": { en: "Position" },
  "Entrada": { en: "Clock In" },
  "Salida": { en: "Clock Out" },
  "Horas": { en: "Hours" },
  "Acción": { en: "Action" },
  "Activos": { en: "Active" },
  "Inactivos": { en: "Inactive" },
  "Control Horario": { en: "Time Tracking" },
  "Registro de Entrada": { en: "Clock In Record" },
  "El empleado ha registrado su entrada correctamente": { en: "Employee has clocked in successfully" },
  "Registro de Salida": { en: "Clock Out Record" },
  "El empleado ha registrado su salida correctamente": { en: "Employee has clocked out successfully" },
  "Descanso iniciado": { en: "Break started" },
  "El empleado ha iniciado su descanso": { en: "Employee has started their break" },
  "Descanso finalizado": { en: "Break ended" },
  "El empleado ha finalizado su descanso": { en: "Employee has ended their break" },
  "Fin Descanso": { en: "End Break" },
  "Failed to update employee status": { en: "Failed to update employee status" },
  "Failed to start break": { en: "Failed to start break" },
  "Failed to end break": { en: "Failed to end break" },
  "Activo": { en: "Active" },
  "Break": { en: "Break" },
  "Inactivo": { en: "Inactive" },
  "Último Turno": { en: "Last Shift" },
  "Tarifa": { en: "Rate" },
  "Fecha": { en: "Date" },
  "Propinas": { en: "Tips" },
  "Mesera": { en: "Waitress" },
  "Cocinero": { en: "Cook" },
  "Cajera": { en: "Cashier" },
  "Gerente": { en: "Manager" },
  
  // Reports
  "Reportes e Insights": { en: "Reports & Insights" },
  "Dashboard": { en: "Dashboard" },
  "Ingresos": { en: "Revenue" },
  "Ventas Totales": { en: "Total Sales" },
  "Hoy": { en: "Today" },
  "Ticket Promedio": { en: "Average Ticket" },
  "Transacciones": { en: "Transactions" },
  "vs ayer": { en: "vs yesterday" },
  "Ventas Semanales": { en: "Weekly Sales" },
  "Últimos 7 días": { en: "Last 7 days" },
  "Exportar": { en: "Export" },
  "Ventas ($)": { en: "Sales ($)" },
  "Clientes": { en: "Customers" },
  "Ventas por Categoría": { en: "Sales by Category" },
  "Distribución de ventas": { en: "Sales distribution" },
  "Top Productos": { en: "Top Products" },
  "Productos más vendidos": { en: "Best-selling products" },
  "Ventas": { en: "Sales" },
  "Exportar Datos": { en: "Export Data" },
  "Informe exportado correctamente": { en: "Report exported successfully" },
  "Exportar a Excel": { en: "Export to Excel" },
  "Ingresos por Periodo": { en: "Revenue by Period" },
  "Ventas mensuales": { en: "Monthly sales" },
  "Ingresos por Sucursal": { en: "Revenue by Branch" },
  "Último mes": { en: "Last month" },
  "Resumen Financiero": { en: "Financial Summary" },
  "Actual": { en: "Current" },
  "Diferencia": { en: "Difference" },
  "Ingresos Totales": { en: "Total Revenue" },
  "Costo de Ventas": { en: "Cost of Sales" },
  "Margen Bruto": { en: "Gross Margin" },
  "Gastos Operativos": { en: "Operating Expenses" },
  "Ganancia Neta": { en: "Net Profit" },
  
  
  // Settings
  "Administra la configuración de tu restaurante": { en: "Manage your restaurant settings" },
  "Restaurante": { en: "Restaurant" },
  "Pagos": { en: "Payments" },
  "Integraciones": { en: "Integrations" },
  "Idioma / Language": { en: "Language" },
  "Avanzado": { en: "Advanced" },
  "Información del Restaurante": { en: "Restaurant Information" },
  "Actualiza la información básica de tu restaurante": { en: "Update your restaurant's basic information" },
  "Aquí podrás ingresar nombre, dirección y datos de contacto del restaurante": { en: "This section will contain fields for restaurant name, address, contact info, etc." },
  "Configura la información básica de tu restaurante": { en: "Configure your restaurant's basic information" },
  "Nombre del Restaurante": { en: "Restaurant Name" },
  "Tipo de Restaurante": { en: "Restaurant Type" },
  "Selecciona un tipo": { en: "Select a type" },
  "Teléfono": { en: "Phone" },
  "Email": { en: "Email" },
  "Calle Principal #123": { en: "Main Street #123" },
  "Ciudad": { en: "City" },
  "Estado/Provincia": { en: "State/Province" },
  "Código Postal": { en: "Postal Code" },
  "Preferencias de Operación": { en: "Operation Preferences" },
  "Configura cómo opera tu restaurante": { en: "Configure how your restaurant operates" },
  "Horario de Apertura": { en: "Opening Time" },
  "Horario de Cierre": { en: "Closing Time" },
  "Horarios de Atención": { en: "Business Hours" },
  "Define los horarios de operación del restaurante": { en: "Set your restaurant's operating hours" },
  "Incluye horarios de operación, días festivos y horarios especiales": { en: "This section will contain settings for operating hours, holidays, special schedules, etc." },
  "Opciones Generales": { en: "General Options" },
  "Propina automática (grupos > 6)": { en: "Automatic gratuity (groups > 6)" },
  "Permitir pedidos en línea": { en: "Allow online orders" },
  "Permitir reservaciones de mesa": { en: "Allow table reservations" },
  "Tasa de Impuesto Predeterminada": { en: "Default Tax Rate" },
  "Configuración de Pagos": { en: "Payment Settings" },
  "Métodos de Pago": { en: "Payment Methods" },
  "Configura los métodos de pago aceptados": { en: "Configure accepted payment methods" },
  "Contendrá integraciones de pago y configuraciones de caja": { en: "This section will contain payment gateway integrations, cash settings, etc." },
  "Configura tus métodos de pago y procesadores": { en: "Configure your payment methods and processors" },
  "Métodos de Pago Aceptados": { en: "Accepted Payment Methods" },
  "Tarjetas de crédito": { en: "Credit cards" },
  "Tarjetas de débito": { en: "Debit cards" },
  "Pagos móviles (Apple Pay, Google Pay)": { en: "Mobile payments (Apple Pay, Google Pay)" },
  "Tarjetas de regalo": { en: "Gift cards" },
  "Procesador de Pagos": { en: "Payment Processor" },
  "Selecciona un procesador de pagos": { en: "Select a payment processor" },
  "Clave API": { en: "API Key" },
  "Opciones de Propina": { en: "Tip Options" },
  "Opción 1": { en: "Option 1" },
  "Opción 2": { en: "Option 2" },
  "Opción 3": { en: "Option 3" },
  "Conecta tu POS con otros servicios": { en: "Connect your POS with other services" },
  "Aquí podrás gestionar usuarios, roles y permisos": { en: "This section will contain user management, role settings, permissions, etc." },
  "Software Contable": { en: "Accounting Software" },
  "Selecciona un software contable": { en: "Select accounting software" },
  "Conectar": { en: "Connect" },
  "Plataformas de Entrega": { en: "Delivery Platforms" },
  "Marketing": { en: "Marketing" },
  "Clave API de Mailchimp": { en: "Mailchimp API Key" },
  "Selecciona tu idioma preferido": { en: "Select your preferred language" },
  
  
  // Misc
  "Funcionalidad no implementada": { en: "Functionality not implemented" },
  "Esta opción estará disponible próximamente": { en: "This option will be available soon" },
  "Menú Principal": { en: "Main Menu" },
  "Welcome to Your Restaurant POS": { en: "Welcome to Your Restaurant POS" },
  "Start managing your restaurant operations": { en: "Start managing your restaurant operations" },
  
  // Additional translations for inventory service
  "Suprimir imagen": { en: "Remove image" },
  "Imagen": { en: "Image" },
  "Recetas": { en: "Recipes" },
  "¿Estás seguro de que quieres eliminar este producto?": { en: "Are you sure you want to delete this product?" },
  "Cargando...": { en: "Loading..." },
  "Creado": { en: "Created" },
  "Actualizado": { en: "Updated" },
  "Agregar Grupo": { en: "Add Group" },
  "Editar Grupo": { en: "Edit Group" },
  "Agregar Opción": { en: "Add Option" },
  "Nombre de Opción": { en: "Option name" },
  "Precio Extra": { en: "Extra" },
  "Precio Adicional": { en: "Extra price" },
  "Agregar Empleado": { en: "Add Employee" },
  "Editar empleado": { en: "Edit employee" },
  "Último Descanso": { en: "Last Break" },
  "Inicio Descanso": { en: "Break Start" },
  "Fin Descanso": { en: "Break End" },
  "No hay registros de horario completados": { en: "No completed time records" },
  "Gestión de Mesas": { en: "Table Layout Management" },
  "Configura el plano y asignación de mesas": { en: "Configure your restaurant's floor plan and table assignments" },
  "Agregar, editar y eliminar mesas": { en: "Add, edit, and remove tables" },
  "Crear y administrar secciones": { en: "Create and manage sections (dining areas)" },
  "Posicionar mesas en el plano": { en: "Position tables visually on the floor plan" },
  "Establecer propiedades de mesa": { en: "Set table properties like capacity and section" },
  "Abrir Editor de Mesas": { en: "Open Table Layout Editor" },
  "Configura tu sistema POS": { en: "Configure your restaurant POS system" },
  "Restaurante": { en: "Restaurant" },
  "Mesas": { en: "Tables" },
  "Pagos": { en: "Payment" },
  "Personal": { en: "Staff" },
  "Notificaciones": { en: "Notifications" },
  "Configuración de Notificaciones": { en: "Notification Settings" },
  "Configura alertas y notificaciones": { en: "Configure alerts and notifications" },
  "Configuraciones para alertas, notificaciones y recordatorios": { en: "This section will contain settings for alerts, notifications, and reminders." },
  "Impresoras": { en: "Printers" },
  "Configuración de Impresoras": { en: "Printer Setup" },
  "Configura impresoras de recibos y cocina": { en: "Configure receipt and kitchen printers" },
  "Conexiones de impresoras, plantillas y ajustes": { en: "This section will contain printer connections, templates, and settings." },
  "Idioma": { en: "Language" },
  "Idioma y Región": { en: "Language & Locale" },
  "Configura el idioma y preferencias regionales": { en: "Set language and regional preferences" },
  "Selecciona idioma, formatos de fecha y moneda": { en: "This section will contain language selection, date formats, currency settings, etc." },
  "Sistema": { en: "System" },
  "Información del Sistema": { en: "System Information" },
  "Consulta detalles del sistema y realiza mantenimiento": { en: "View system details and perform maintenance" },
  "Información del sistema, opciones de respaldo y herramientas de mantenimiento": { en: "This section will contain system info, backup options, and maintenance tools." },
  "Editor de Plano de Mesas": { en: "Table Layout Editor" },
  "Seleccionar Sección": { en: "Select Section" },
  "Agregar Mesa": { en: "Add Table" },
  "Agregar Sección": { en: "Add Section" },
  "Nueva Sección": { en: "Add New Section" },
  "Agregar Elemento": { en: "Add Element" },
  "Sin sección": { en: "No section" },
  "Secciones del Restaurante": { en: "Restaurant Sections" },
  "Gestiona las áreas de comedor": { en: "Manage dining areas" },
  "El editor de mesas te permite crear y administrar el plano de tu restaurante. Puedes:": { en: "The table layout editor allows you to create and manage your restaurant floor plan. You can:" },
  "No se encontraron secciones": { en: "No sections found" },
  "Mesas del Restaurante": { en: "Tables" },
  "Todas las mesas de tu restaurante": { en: "All tables in your restaurant" },
  "No se encontraron mesas": { en: "No tables found" },
  "Figuras": { en: "Shapes" },
  "Todas las figuras en este plano": { en: "All shapes in this map" },
  "No se encontraron figuras": { en: "No shapes found" },
  "Agregar Figura": { en: "Add Shape" },
  "Vista Previa del Plano": { en: "Layout Preview" },
  "Arrastra las mesas para posicionarlas en el plano": { en: "Drag tables to position them on the map" },
  "Guardar Cambios": { en: "Save Changes" },
  "Nueva Mesa": { en: "Add New Table" },
  "Crea una nueva mesa para el plano del restaurante.": { en: "Create a new table for your restaurant layout." },
  "Número de Mesa": { en: "Table Number" },
  "Tipo de Mesa": { en: "Table Type" },
  "Selecciona un tipo": { en: "Select a type" },
  "Cuadrada": { en: "Square" },
  "Redonda": { en: "Round" },
  "Ancho (px)": { en: "Width (px)" },
  "Alto (px)": { en: "Height (px)" },
  "Capacidad": { en: "Capacity" },
  "Sección": { en: "Section" },
  "Selecciona una sección": { en: "Select a section" },
  "Rotación (grados)": { en: "Rotation (deg)" },
  "Color": { en: "Color" },
  "Agregar Mesa al Plano": { en: "Add Table" },
  "Nuevo Elemento": { en: "Add New Element" },
  "Configura el nuevo elemento del plano": { en: "Configure the new map element" },
  "Tipo": { en: "Type" },
  "Selecciona tipo": { en: "Select type" },
  "Rectángulo": { en: "Rectangle" },
  "Círculo": { en: "Circle" },
  "Línea": { en: "Line" },
  "Texto": { en: "Text" },
  "Agregar Elemento al Plano": { en: "Add Element" },
  "Editar Figura": { en: "Edit Shape" },
  "Actualiza las propiedades de la figura.": { en: "Update shape properties." },
  "Editar Mesa": { en: "Edit Table" },
  "Actualiza la información de la mesa.": { en: "Update table information." },
  "Editar Sección": { en: "Edit Section" },
  "Crear una nueva área de comedor para tu restaurante.": { en: "Create a new dining area for your restaurant." },
  "Nombre de la Sección": { en: "Section Name" },
  "Actualiza la información de la sección.": { en: "Update section information." },
  "Agregar Color de Mesa": { en: "Add Table Color" },
  "Selecciona un nuevo color": { en: "Select New Color" },
  "Agregar Color": { en: "Add Color" },
  "Confirmar Eliminación": { en: "Confirm Deletion" },
  "¿Estás seguro de que deseas eliminar este elemento? Esta acción no se puede deshacer.": { en: "Are you sure you want to delete this item? This action cannot be undone." },
  "Mesa eliminada": { en: "Table Deleted" },
  "La mesa se ha eliminado correctamente.": { en: "Table has been removed successfully." },
  "Figura eliminada": { en: "Shape Deleted" },
  "La figura se ha eliminado correctamente.": { en: "Shape has been removed successfully." },
  "Sección eliminada": { en: "Section Deleted" },
  "La sección se ha eliminado correctamente.": { en: "Section has been removed successfully." },
  "No se puede eliminar la sección": { en: "Cannot Delete Section" },
  "Esta sección contiene mesas. Muévelas o elimínalas primero.": { en: "This section contains tables. Move or delete them first." }
};

interface LanguageProviderProps {
  children: ReactNode;
}

type LanguageContextType = {
  language: Language;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  language: "es",
  t: (key) => key,
});

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  // Always use Spanish
  const [language, _setLanguage] = useState<Language>("es");

  // Translation function that returns Spanish text
  const englishToSpanish = React.useMemo(() => {
    const map: Record<string, string> = {};
    for (const [es, val] of Object.entries(translations)) {
      map[val.en] = es;
    }
    return map;
  }, []);

  const t = (key: string): string => {
    if (englishToSpanish[key]) {
      return englishToSpanish[key];
    }
    if (translations[key]) {
      return key; // key is already Spanish
    }
    return key;
  };

  const contextValue = {
    language,
    t,
  };

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
