
import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "es";

type TranslationEntry = {
  en: string;
};

type TranslationDictionary = {
  [key: string]: TranslationEntry;
};

// A simplified translation dictionary that only contains English translations
const translations: TranslationDictionary = {
  // Navigation
  "Inicio": { en: "Home" },
  "Punto de Venta": { en: "Point of Sale" },
  "Pedidos en Línea": { en: "Online Orders" },
  "Empleados": { en: "Employees" },
  "Menú": { en: "Menu" },
  "Inventario": { en: "Inventory" },
  "Fidelización": { en: "Loyalty" },
  "Reportes": { en: "Reports" },
  "Personalizaciones": { en: "Customizations" },
  "Ayuda": { en: "Help" },
  "Configuración": { en: "Settings" },
  "Dispositivos": { en: "Hardware" },
  
  // Common Words
  "Guardar": { en: "Save" },
  "Cancelar": { en: "Cancel" },
  "Eliminar": { en: "Delete" },
  "Editar": { en: "Edit" },
  "Nuevo": { en: "New" },
  "Buscar": { en: "Search" },
  "Filtrar": { en: "Filter" },
  "Detalles": { en: "Details" },
  "Cerrar": { en: "Close" },
  "Cerrar sesión": { en: "Log Out" },
  "Aceptar": { en: "Accept" },
  "Rechazar": { en: "Reject" },
  "Siguiente": { en: "Next" },
  "Anterior": { en: "Previous" },
  "Volver": { en: "Back" },
  "Ingresa el código": { en: "Enter code" },
  "Por favor ingresa un código de acceso.": { en: "Please enter an access code." },
  "Bienvenido": { en: "Welcome" },
  "Código inválido": { en: "Invalid Code" },
  "Código de acceso no reconocido.": { en: "Access code not recognized." },
  "Error al validar el código.": { en: "Failed to validate code." },
  "Introduce el código de acceso": { en: "Enter Access Code" },
  "Entrar": { en: "Enter" },
  "Mesas seleccionadas": { en: "Selected tables" },
  "Cancelar Fusión": { en: "Cancel Merge" },
  "Iniciar Orden Fusionada": { en: "Start Merged Order" },
  "Enlazando": { en: "Linking" },
  "Cancelar Enlace": { en: "Cancel Link" },
  "Confirmar Enlace": { en: "Confirm Link" },
  "Gestión de Órdenes": { en: "Order Management" },
  "Administra tus órdenes activas": { en: "Manage your active orders" },
  "Nueva Orden": { en: "New Order" },
  "Órdenes Pendientes": { en: "Pending Orders" },
  "En Cocina": { en: "In Kitchen" },
  "Por Pagar": { en: "To Pay" },
  "Ingresos Activos": { en: "Active Revenue" },
  "Todas las Órdenes": { en: "All Orders" },
  "Pendiente": { en: "Pending" },
  "En Espera": { en: "On Hold" },
  "Mis Órdenes Activas": { en: "My Active Orders" },
  "No se encontraron órdenes activas": { en: "No active orders found" },
  "Crear Nueva Orden": { en: "Create New Order" },
  "Para llevar": { en: "Takeout" },
  "cliente(s)": { en: "client(s)" },
  "Iniciada a las": { en: "Started at" },
  "Ver": { en: "View" },
  "Agregar Artículos": { en: "Add Items" },
  "Pagar": { en: "Pay" },
  "Detalles de Orden": { en: "Order Details" },
  "ID de Orden": { en: "Order ID" },
  "Creada": { en: "Created" },
  "Mesero": { en: "Server" },
  "Clientes": { en: "Clients" },
  "Artículos de la Orden": { en: "Order Items" },
  "Procesar Pago": { en: "Process Payment" },
  "Confirmar Fusión": { en: "Confirm Merge" },
  "¿Deseas fusionar la orden de la Mesa": { en: "Do you want to merge the order from Table" },
  "a la Mesa": { en: "to Table" },
  "Fusionando...": { en: "Merging..." },
  "Confirmar": { en: "Confirm" },
  "Confirmar Cambio de Mesa": { en: "Confirm Table Change" },
  "Mover orden de la Mesa": { en: "Move order from Table" },
  "Moviendo...": { en: "Moving..." },
  "Desvincular Mesa": { en: "Unlink Table" },
  "Elige cómo desvincular la mesa": { en: "Choose how to unlink table" },
  "Desvinculando...": { en: "Unlinking..." },
  "Desvincular Esta Mesa": { en: "Unlink This Table" },
  "Desvincular Todo el Grupo": { en: "Unlink Entire Group" },
  "Selecciona Número de Clientes": { en: "Select Number of Guests" },
  "Selecciona número de clientes (máx": { en: "Select number of guests (max" },
  
  // POS
  "Categorías": { en: "Categories" },
  "Todas": { en: "All" },
  "Añadir a Orden": { en: "Add to Order" },
  "Mesa": { en: "Table" },
  "Cliente": { en: "Customer" },
  "Elementos": { en: "Items" },
  "Cantidad": { en: "Quantity" },
  "Precio": { en: "Price" },
  "Subtotal": { en: "Subtotal" },
  "Impuesto": { en: "Tax" },
  "Total": { en: "Total" },
  "Descuento": { en: "Discount" },
  "Propina": { en: "Tip" },
  "Pagar": { en: "Pay" },
  "Imprimir": { en: "Print" },
  "Cancelar Orden": { en: "Cancel Order" },
  "Modificar": { en: "Modify" },
  "Agregar Nota": { en: "Add Note" },
  "Sin elementos en la orden": { en: "No items in order" },
  "Agregar productos para continuar": { en: "Add products to continue" },
  "Resumen de Orden": { en: "Order Summary" },
  "Nueva Orden": { en: "New Order" },
  "Orden para": { en: "Order for" },
  "Para llevar": { en: "To Go" },
  "Para comer aquí": { en: "Dine In" },
  "Métodos de Pago": { en: "Payment Methods" },
  "Efectivo": { en: "Cash" },
  "Tarjeta": { en: "Card" },
  "Confirmar Pago": { en: "Confirm Payment" },
  "Orden Completada": { en: "Order Completed" },
  "Note": { en: "Note" },
  "Payment confirmed and order processed successfully.": { en: "Payment confirmed and order processed successfully." },
  
  // Menu Page
  "Gestión del Menú": { en: "Menu Management" },
  "Desayuno": { en: "Breakfast" },
  "Almuerzo": { en: "Lunch" },
  "Cena": { en: "Dinner" },
  "Menú de Desayuno": { en: "Breakfast Menu" },
  "Menú de Almuerzo": { en: "Lunch Menu" },
  "Menú de Cena": { en: "Dinner Menu" },
  "Edición de producto": { en: "Product Editing" },
  "Agregar Producto": { en: "Add Product" },
  "Agregar nuevo producto": { en: "Add New Product" },
  
  // Inventory Page
  "Dashboard de Inventario": { en: "Inventory Dashboard" },
  "Estado de Inventario": { en: "Inventory Status" },
  "Costeo de Recetas": { en: "Recipe Costing" },
  "Producto": { en: "Product" },
  "Categoría": { en: "Category" },
  "Estado": { en: "Status" },
  "Costo": { en: "Cost" },
  "Alto": { en: "High" },
  "Medio": { en: "Medium" },
  "Bajo": { en: "Low" },
  "Alerta de Inventario": { en: "Inventory Alert" },
  "productos están por debajo del nivel mínimo requerido": { en: "products are below the minimum required level" },
  "Carnes": { en: "Meats" },
  "Lácteos": { en: "Dairy" },
  "Panadería": { en: "Bakery" },
  "Vegetales": { en: "Vegetables" },
  "Congelados": { en: "Frozen" },
  "Bebidas": { en: "Beverages" },
  "Insumos": { en: "Supplies" },
  "Costo de Ingredientes": { en: "Ingredients Cost" },
  "Precio de Venta": { en: "Selling Price" },
  "Beneficio": { en: "Profit" },
  "Margen %": { en: "Margin %" },
  "Proveedor": { en: "Supplier" },
  "Unidad": { en: "Unit" },
  "Costo por Unidad": { en: "Cost per Unit" },
  "No especificado": { en: "Not specified" },
  "No hay productos en el inventario": { en: "No products in inventory" },
  "Introduce la información del producto para añadirlo al inventario.": { en: "Enter product information to add it to inventory." },
  "Vista previa de imagen": { en: "Image preview" },
  "Subir imagen": { en: "Upload image" },
  "Guardando...": { en: "Saving..." },
  "Cambiar imagen": { en: "Change image" },
  "Producto agregado": { en: "Product added" },
  "El producto ha sido agregado al inventario": { en: "The product has been added to the inventory" },
  "No se pudo agregar el producto": { en: "Could not add the product" },
  "Producto actualizado": { en: "Product updated" },
  "El producto ha sido actualizado correctamente": { en: "The product has been updated successfully" },
  "No se pudo actualizar el producto": { en: "Could not update the product" },
  "Producto eliminado": { en: "Product deleted" },
  "El producto ha sido eliminado del inventario": { en: "The product has been removed from inventory" },
  "No se pudo eliminar el producto": { en: "Could not delete the product" },
  "¿Estás seguro de que quieres eliminar este producto?": { en: "Are you sure you want to delete this product?" },
  "Editar Producto": { en: "Edit Product" },
  "Modifica la información del producto.": { en: "Modify the product information." },
  "Cargando inventario...": { en: "Loading inventory..." },
  "No se pudo cargar el inventario": { en: "Could not load inventory" },
  "Image": { en: "Image" },
  "Actions": { en: "Actions" },
  
  // Online Orders
  "Pendientes": { en: "Pending" },
  "En Preparación": { en: "In Preparation" },
  "Listos": { en: "Ready" },
  "Historial": { en: "History" },
  "No hay pedidos pendientes": { en: "No pending orders" },
  "No hay pedidos en preparación": { en: "No orders in preparation" },
  "No hay pedidos listos para entrega": { en: "No orders ready for delivery" },
  "No hay historial de pedidos": { en: "No order history" },
  "Preparar": { en: "Prepare" },
  "Marcar Listo": { en: "Mark Ready" },
  "Entregar": { en: "Deliver" },
  "Estado actualizado": { en: "Status updated" },
  "actualizada a": { en: "updated to" },
  "Fuente": { en: "Source" },
  "Hora": { en: "Time" },
  "ETA": { en: "ETA" },
  "Artículos": { en: "Items" },
  "Dirección": { en: "Address" },
  "pending": { en: "pending" },
  "preparing": { en: "preparing" },
  "ready": { en: "ready" },
  "delivered": { en: "delivered" },
  "cancelled": { en: "cancelled" },
  "Pending": { en: "Pending" },
  "Preparing": { en: "Preparing" },
  "Ready": { en: "Ready" },
  "Delivered": { en: "Delivered" },
  "Cancelled": { en: "Cancelled" },
  
  // Employees
  "Gestión de Empleados": { en: "Employee Management" },
  "Gestión de Personal": { en: "Staff Management" },
  "Administra a tus empleados y permisos": { en: "Manage your employees and permissions" },
  "Empleados Activos": { en: "Active Employees" },
  "Personal actualmente en turno": { en: "Staff currently on shift" },
  "Empleados Inactivos": { en: "Inactive Employees" },
  "Personal disponible para turno": { en: "Staff available for shift" },
  "Registro de Horas": { en: "Time Records" },
  "Resumen de horas y propinas": { en: "Summary of hours and tips" },
  "No hay empleados activos en este momento": { en: "No active employees at this time" },
  "No hay empleados inactivos en este momento": { en: "No inactive employees at this time" },
  "Nombre": { en: "Name" },
  "Cargo": { en: "Position" },
  "Entrada": { en: "Clock In" },
  "Salida": { en: "Clock Out" },
  "Horas": { en: "Hours" },
  "Acción": { en: "Action" },
  "Activos": { en: "Active" },
  "Inactivos": { en: "Inactive" },
  "Control Horario": { en: "Time Tracking" },
  "Registro de Entrada": { en: "Clock In Record" },
  "El empleado ha registrado su entrada correctamente": { en: "Employee has clocked in successfully" },
  "Registro de Salida": { en: "Clock Out Record" },
  "El empleado ha registrado su salida correctamente": { en: "Employee has clocked out successfully" },
  "Descanso iniciado": { en: "Break started" },
  "El empleado ha iniciado su descanso": { en: "Employee has started their break" },
  "Descanso finalizado": { en: "Break ended" },
  "El empleado ha finalizado su descanso": { en: "Employee has ended their break" },
  "Fin Descanso": { en: "End Break" },
  "Failed to update employee status": { en: "Failed to update employee status" },
  "Failed to start break": { en: "Failed to start break" },
  "Failed to end break": { en: "Failed to end break" },
  "Activo": { en: "Active" },
  "Break": { en: "Break" },
  "Inactivo": { en: "Inactive" },
  "Último Turno": { en: "Last Shift" },
  "Tarifa": { en: "Rate" },
  "Fecha": { en: "Date" },
  "Propinas": { en: "Tips" },
  "Mesera": { en: "Waitress" },
  "Cocinero": { en: "Cook" },
  "Cajera": { en: "Cashier" },
  "Gerente": { en: "Manager" },
  
  // Reports
  "Reportes e Insights": { en: "Reports & Insights" },
  "Dashboard": { en: "Dashboard" },
  "Ingresos": { en: "Revenue" },
  "Ventas Totales": { en: "Total Sales" },
  "Hoy": { en: "Today" },
  "Ticket Promedio": { en: "Average Ticket" },
  "Transacciones": { en: "Transactions" },
  "vs ayer": { en: "vs yesterday" },
  "Ventas Semanales": { en: "Weekly Sales" },
  "Últimos 7 días": { en: "Last 7 days" },
  "Exportar": { en: "Export" },
  "Ventas ($)": { en: "Sales ($)" },
  "Clientes": { en: "Customers" },
  "Ventas por Categoría": { en: "Sales by Category" },
  "Distribución de ventas": { en: "Sales distribution" },
  "Top Productos": { en: "Top Products" },
  "Productos más vendidos": { en: "Best-selling products" },
  "Ventas": { en: "Sales" },
  "Exportar Datos": { en: "Export Data" },
  "Informe exportado correctamente": { en: "Report exported successfully" },
  "Exportar a Excel": { en: "Export to Excel" },
  "Ingresos por Periodo": { en: "Revenue by Period" },
  "Ventas mensuales": { en: "Monthly sales" },
  "Ingresos por Sucursal": { en: "Revenue by Branch" },
  "Último mes": { en: "Last month" },
  "Resumen Financiero": { en: "Financial Summary" },
  "Actual": { en: "Current" },
  "Diferencia": { en: "Difference" },
  "Ingresos Totales": { en: "Total Revenue" },
  "Costo de Ventas": { en: "Cost of Sales" },
  "Margen Bruto": { en: "Gross Margin" },
  "Gastos Operativos": { en: "Operating Expenses" },
  "Ganancia Neta": { en: "Net Profit" },
  
  // Loyalty
  "Fidelización y Regalos": { en: "Loyalty and Gifts" },
  "Programa de Puntos": { en: "Points Program" },
  "Tarjetas de Regalo": { en: "Gift Cards" },
  "Campañas de Email": { en: "Email Campaigns" },
  "Buscar Cliente": { en: "Search Customer" },
  "Busque por nombre o teléfono": { en: "Search by name or phone" },
  "Buscar cliente": { en: "Search customer" },
  "Nombre, teléfono o email": { en: "Name, phone or email" },
  "Búsqueda de cliente": { en: "Customer search" },
  "Perfil Cliente": { en: "Customer Profile" },
  "Puntos acumulados": { en: "Points accumulated" },
  "de 1000 para recompensa": { en: "of 1000 for reward" },
  "Progreso hacia próxima recompensa": { en: "Progress towards next reward" },
  "Nivel": { en: "Level" },
  "Último pedido": { en: "Last order" },
  "Total gastado": { en: "Total spent" },
  "Redimir Recompensa": { en: "Redeem Reward" },
  "Recompensas": { en: "Rewards" },
  "Activar Tarjeta": { en: "Activate Card" },
  "Escanee o introduzca el código": { en: "Scan or enter code" },
  "Número de Tarjeta": { en: "Card Number" },
  "Monto": { en: "Amount" },
  "Activar": { en: "Activate" },
  "Tarjeta Activada": { en: "Card Activated" },
  "La tarjeta de regalo ha sido activada correctamente": { en: "The gift card has been activated successfully" },
  "Tarjetas Activas": { en: "Active Cards" },
  "Gestión de tarjetas de regalo": { en: "Gift card management" },
  "Número": { en: "Number" },
  "Monto Original": { en: "Original Amount" },
  "Balance": { en: "Balance" },
  "Verificar": { en: "Verify" },
  "Checar balance": { en: "Check balance" },
  "Nueva Campaña": { en: "New Campaign" },
  "Configure una nueva campaña de marketing": { en: "Set up a new marketing campaign" },
  "Nombre de Campaña": { en: "Campaign Name" },
  "Nombre de la campaña": { en: "Name of the campaign" },
  "Tipo de Campaña": { en: "Campaign Type" },
  "Notificación Push": { en: "Push Notification" },
  "Fecha de Envío": { en: "Send Date" },
  "Crear Campaña": { en: "Create Campaign" },
  "Campaña creada": { en: "Campaign created" },
  "La campaña se ha creado correctamente": { en: "The campaign has been created successfully" },
  "Campañas Recientes": { en: "Recent Campaigns" },
  "Historial y estadísticas de campañas": { en: "Campaign history and statistics" },
  "Tipo": { en: "Type" },
  "Enviados": { en: "Sent" },
  "Abiertos": { en: "Opened" },
  "Conversión": { en: "Conversion" },
  "Promoción de Verano": { en: "Summer Promotion" },
  "Descuento Fin de Semana": { en: "Weekend Discount" },
  "Nuevo Menú": { en: "New Menu" },

  // Hardware
  "Simulación de Hardware": { en: "Hardware Simulation" },
  "Hardware POS": { en: "POS Hardware" },
  "Modo Quiosco": { en: "Kiosk Mode" },
  "Impresora de Recibos": { en: "Receipt Printer" },
  "Gestione su impresora de recibos térmica": { en: "Manage your thermal receipt printer" },
  "Estado de la impresora": { en: "Printer status" },
  "Conectada": { en: "Connected" },
  "Desconectada": { en: "Disconnected" },
  "Conectar/Desconectar": { en: "Connect/Disconnect" },
  "Impresora conectada": { en: "Printer connected" },
  "La impresora está lista para imprimir": { en: "The printer is ready to print" },
  "Impresora desconectada": { en: "Printer disconnected" },
  "La impresora ha sido desconectada": { en: "The printer has been disconnected" },
  "Imprimir Página de Prueba": { en: "Print Test Page" },
  "Impresión de prueba": { en: "Test print" },
  "Se ha enviado una página de prueba a la impresora": { en: "A test page has been sent to the printer" },
  "Error": { en: "Error" },
  "La impresora no está conectada": { en: "The printer is not connected" },
  "Cajón de Efectivo": { en: "Cash Drawer" },
  "Controle su cajón de efectivo": { en: "Control your cash drawer" },
  "Estado del cajón": { en: "Drawer status" },
  "Abierto": { en: "Open" },
  "Cerrado": { en: "Closed" },
  "Abrir Cajón": { en: "Open Drawer" },
  "Cajón abierto": { en: "Drawer open" },
  "El cajón de efectivo ha sido abierto": { en: "The cash drawer has been opened" },
  "Lector de Tarjetas": { en: "Card Reader" },
  "Configure su lector de tarjetas": { en: "Configure your card reader" },
  "Estado del lector": { en: "Reader status" },
  "Conectado": { en: "Connected" },
  "Desconectado": { en: "Disconnected" },
  "Lector conectado": { en: "Reader connected" },
  "El lector de tarjetas está listo para usar": { en: "The card reader is ready to use" },
  "Lector desconectado": { en: "Reader disconnected" },
  "El lector de tarjetas ha sido desconectado": { en: "The card reader has been disconnected" },
  "Probar Conexión": { en: "Test Connection" },
  "Prueba de conexión completada con éxito": { en: "Connection test completed successfully" },
  "Pantalla de Cliente": { en: "Customer Display" },
  "Configure la pantalla orientada al cliente": { en: "Configure the customer-facing display" },
  "Estado de la pantalla": { en: "Display status" },
  "Brillo": { en: "Brightness" },
  "Brillo ajustado": { en: "Brightness adjusted" },
  "El brillo de la pantalla ha sido ajustado": { en: "The screen brightness has been adjusted" },
  "Probar Pantalla": { en: "Test Display" },
  "Prueba de visualización completada con éxito": { en: "Display test completed successfully" },
  "Configure el modo de quiosco de autoservicio": { en: "Configure the self-service kiosk mode" },
  "Activar modo quiosco": { en: "Enable kiosk mode" },
  "Modo quiosco activado": { en: "Kiosk mode enabled" },
  "Ha entrado en modo quiosco": { en: "You have entered kiosk mode" },
  "Modo quiosco desactivado": { en: "Kiosk mode disabled" },
  "Ha salido del modo quiosco": { en: "You have exited kiosk mode" },
  "Opciones del Quiosco": { en: "Kiosk Options" },
  "Permitir auto-pago": { en: "Allow self-checkout" },
  "Permitir modificaciones": { en: "Allow modifications" },
  "Permitir pago en efectivo": { en: "Allow cash payment" },
  "Configuración guardada": { en: "Configuration saved" },
  "La configuración de auto-pago ha sido actualizada": { en: "The self-checkout configuration has been updated" },
  "La configuración de modificaciones ha sido actualizada": { en: "The modifications configuration has been updated" },
  "La configuración de pago en efectivo ha sido actualizada": { en: "The cash payment configuration has been updated" },
  "Previsualizar Modo Quiosco": { en: "Preview Kiosk Mode" },
  "Vista previa": { en: "Preview" },
  "Cargando vista previa del modo quiosco...": { en: "Loading kiosk mode preview..." },
  
  // Settings
  "Administra la configuración de tu restaurante": { en: "Manage your restaurant settings" },
  "Restaurante": { en: "Restaurant" },
  "Pagos": { en: "Payments" },
  "Integraciones": { en: "Integrations" },
  "Idioma / Language": { en: "Language" },
  "Avanzado": { en: "Advanced" },
  "Información del Restaurante": { en: "Restaurant Information" },
  "Actualiza la información básica de tu restaurante": { en: "Update your restaurant's basic information" },
  "Aquí podrás ingresar nombre, dirección y datos de contacto del restaurante": { en: "This section will contain fields for restaurant name, address, contact info, etc." },
  "Configura la información básica de tu restaurante": { en: "Configure your restaurant's basic information" },
  "Nombre del Restaurante": { en: "Restaurant Name" },
  "Tipo de Restaurante": { en: "Restaurant Type" },
  "Selecciona un tipo": { en: "Select a type" },
  "Teléfono": { en: "Phone" },
  "Email": { en: "Email" },
  "Calle Principal #123": { en: "Main Street #123" },
  "Ciudad": { en: "City" },
  "Estado/Provincia": { en: "State/Province" },
  "Código Postal": { en: "Postal Code" },
  "Preferencias de Operación": { en: "Operation Preferences" },
  "Configura cómo opera tu restaurante": { en: "Configure how your restaurant operates" },
  "Horario de Apertura": { en: "Opening Time" },
  "Horario de Cierre": { en: "Closing Time" },
  "Horarios de Atención": { en: "Business Hours" },
  "Define los horarios de operación del restaurante": { en: "Set your restaurant's operating hours" },
  "Incluye horarios de operación, días festivos y horarios especiales": { en: "This section will contain settings for operating hours, holidays, special schedules, etc." },
  "Opciones Generales": { en: "General Options" },
  "Propina automática (grupos > 6)": { en: "Automatic gratuity (groups > 6)" },
  "Permitir pedidos en línea": { en: "Allow online orders" },
  "Permitir reservaciones de mesa": { en: "Allow table reservations" },
  "Tasa de Impuesto Predeterminada": { en: "Default Tax Rate" },
  "Configuración de Pagos": { en: "Payment Settings" },
  "Métodos de Pago": { en: "Payment Methods" },
  "Configura los métodos de pago aceptados": { en: "Configure accepted payment methods" },
  "Contendrá integraciones de pago y configuraciones de caja": { en: "This section will contain payment gateway integrations, cash settings, etc." },
  "Configura tus métodos de pago y procesadores": { en: "Configure your payment methods and processors" },
  "Métodos de Pago Aceptados": { en: "Accepted Payment Methods" },
  "Tarjetas de crédito": { en: "Credit cards" },
  "Tarjetas de débito": { en: "Debit cards" },
  "Pagos móviles (Apple Pay, Google Pay)": { en: "Mobile payments (Apple Pay, Google Pay)" },
  "Tarjetas de regalo": { en: "Gift cards" },
  "Procesador de Pagos": { en: "Payment Processor" },
  "Selecciona un procesador de pagos": { en: "Select a payment processor" },
  "Clave API": { en: "API Key" },
  "Opciones de Propina": { en: "Tip Options" },
  "Opción 1": { en: "Option 1" },
  "Opción 2": { en: "Option 2" },
  "Opción 3": { en: "Option 3" },
  "Conecta tu POS con otros servicios": { en: "Connect your POS with other services" },
  "Aquí podrás gestionar usuarios, roles y permisos": { en: "This section will contain user management, role settings, permissions, etc." },
  "Software Contable": { en: "Accounting Software" },
  "Selecciona un software contable": { en: "Select accounting software" },
  "Conectar": { en: "Connect" },
  "Plataformas de Entrega": { en: "Delivery Platforms" },
  "Marketing": { en: "Marketing" },
  "Clave API de Mailchimp": { en: "Mailchimp API Key" },
  "Selecciona tu idioma preferido": { en: "Select your preferred language" },
  
  // Help
  "Centro de Ayuda y Soporte": { en: "Help and Support Center" },
  "Preguntas Frecuentes": { en: "Frequently Asked Questions" },
  "Tutoriales": { en: "Tutorials" },
  "Soporte Técnico": { en: "Technical Support" },
  "Actualizaciones": { en: "Updates" },
  "Centro de Soporte 24/7": { en: "24/7 Support Center" },
  "Nuestro equipo está disponible para ayudarte en cualquier momento": { en: "Our team is available to help you at any time" },
  "Disponible 24/7": { en: "Available 24/7" },
  "Respuesta en 2 horas": { en: "Response in 2 hours" },
  "Iniciando chat": { en: "Starting chat" },
  "Conectando con un agente de soporte...": { en: "Connecting with a support agent..." },
  "Iniciar Chat": { en: "Start Chat" },
  "Enviar Solicitud de Soporte": { en: "Send Support Request" },
  "Asunto": { en: "Subject" },
  "Describe tu problema con detalle...": { en: "Describe your problem in detail..." },
  "Enviar Solicitud": { en: "Send Request" },
  "Solicitud enviada": { en: "Request sent" },
  "Nuestro equipo de soporte te responderá en breve": { en: "Our support team will respond shortly" },
  "Actualizaciones Recientes": { en: "Recent Updates" },
  "Mantente al día con las últimas actualizaciones y mejoras": { en: "Stay up to date with the latest updates and improvements" },
  
  // Misc
  "Funcionalidad no implementada": { en: "Functionality not implemented" },
  "Esta opción estará disponible próximamente": { en: "This option will be available soon" },
  "Menú Principal": { en: "Main Menu" },
  "Welcome to Your Restaurant POS": { en: "Welcome to Your Restaurant POS" },
  "Start managing your restaurant operations": { en: "Start managing your restaurant operations" },
  
  // Additional translations for inventory service
  "Suprimir imagen": { en: "Remove image" },
  "Imagen": { en: "Image" },
  "Recetas": { en: "Recipes" },
  "¿Estás seguro de que quieres eliminar este producto?": { en: "Are you sure you want to delete this product?" },
  "Cargando...": { en: "Loading..." },
  "Creado": { en: "Created" },
  "Actualizado": { en: "Updated" },
  "Agregar Grupo": { en: "Add Group" },
  "Editar Grupo": { en: "Edit Group" },
  "Agregar Opción": { en: "Add Option" },
  "Nombre de Opción": { en: "Option name" },
  "Precio Extra": { en: "Extra" },
  "Precio Adicional": { en: "Extra price" },
  "Agregar Empleado": { en: "Add Employee" },
  "Editar empleado": { en: "Edit employee" },
  "Último Descanso": { en: "Last Break" },
  "Inicio Descanso": { en: "Break Start" },
  "Fin Descanso": { en: "Break End" },
  "No hay registros de horario completados": { en: "No completed time records" },
  "Gestión de Mesas": { en: "Table Layout Management" },
  "Configura el plano y asignación de mesas": { en: "Configure your restaurant's floor plan and table assignments" },
  "Agregar, editar y eliminar mesas": { en: "Add, edit, and remove tables" },
  "Crear y administrar secciones": { en: "Create and manage sections (dining areas)" },
  "Posicionar mesas en el plano": { en: "Position tables visually on the floor plan" },
  "Establecer propiedades de mesa": { en: "Set table properties like capacity and section" },
  "Abrir Editor de Mesas": { en: "Open Table Layout Editor" },
  "Configura tu sistema POS": { en: "Configure your restaurant POS system" },
  "Restaurante": { en: "Restaurant" },
  "Mesas": { en: "Tables" },
  "Pagos": { en: "Payment" },
  "Personal": { en: "Staff" },
  "Notificaciones": { en: "Notifications" },
  "Configuración de Notificaciones": { en: "Notification Settings" },
  "Configura alertas y notificaciones": { en: "Configure alerts and notifications" },
  "Configuraciones para alertas, notificaciones y recordatorios": { en: "This section will contain settings for alerts, notifications, and reminders." },
  "Impresoras": { en: "Printers" },
  "Configuración de Impresoras": { en: "Printer Setup" },
  "Configura impresoras de recibos y cocina": { en: "Configure receipt and kitchen printers" },
  "Conexiones de impresoras, plantillas y ajustes": { en: "This section will contain printer connections, templates, and settings." },
  "Idioma": { en: "Language" },
  "Idioma y Región": { en: "Language & Locale" },
  "Configura el idioma y preferencias regionales": { en: "Set language and regional preferences" },
  "Selecciona idioma, formatos de fecha y moneda": { en: "This section will contain language selection, date formats, currency settings, etc." },
  "Sistema": { en: "System" },
  "Información del Sistema": { en: "System Information" },
  "Consulta detalles del sistema y realiza mantenimiento": { en: "View system details and perform maintenance" },
  "Información del sistema, opciones de respaldo y herramientas de mantenimiento": { en: "This section will contain system info, backup options, and maintenance tools." }
};

interface LanguageProviderProps {
  children: ReactNode;
}

type LanguageContextType = {
  language: Language;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  language: "es",
  t: (key) => key,
});

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  // Always use Spanish
  const [language, _setLanguage] = useState<Language>("es");

  // Translation function that returns Spanish text
  const englishToSpanish = React.useMemo(() => {
    const map: Record<string, string> = {};
    for (const [es, val] of Object.entries(translations)) {
      map[val.en] = es;
    }
    return map;
  }, []);

  const t = (key: string): string => {
    if (englishToSpanish[key]) {
      return englishToSpanish[key];
    }
    if (translations[key]) {
      return key; // key is already Spanish
    }
    return key;
  };

  const contextValue = {
    language,
    t,
  };

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
